version: "3.3"

services:
  mysql:
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      MYSQL_DATABASE: emojis
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin